services:
  jenkins:
    build: .
    privileged: true
    user: root
    ports:
      - 9090:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  demo-app:
    image: evanmann/ensf400-final-project:apprun
    ports:
      - "8080:8080" 
    stdin_open: true
    tty: true

  zap:  # <-- Add this service
    image: owasp/zap2docker-stable
    ports:
      - "8081:8080"  # ZAP UI (optional)
      - "9888:8080"  # Proxy port

